events {}

http {

    # -----------------------------------------------
    # Server 1: Port 80 → 443 redirect
    # -----------------------------------------------
    server {
        listen 80;
        server_name localhost;

        return 301 https://$host$request_uri;
    }

    # -----------------------------------------------
    # Server 2: HTTPS (port 443) — main server
    # -----------------------------------------------
    server {
        listen 443 ssl;
        server_name localhost;

        # TLS certificate files
        ssl_certificate     /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        # App container pe traffic forward karo
        location / {
            proxy_pass http://pokedex-app:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

}